-- MySQL Script generated by MySQL Workbench
-- mer. 21 juil. 2021 11:51:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfolio` ;

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`myself`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`myself` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`myself` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(80) NOT NULL,
  `lastname` VARCHAR(80) NOT NULL,
  `role` VARCHAR(150) NULL,
  `about` TEXT NULL,
  `contact` VARCHAR(150) NULL,
  `linkedin` VARCHAR(255) NULL,
  `github` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`project` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `main_img` VARCHAR(100) NULL,
  `desc` TEXT NULL,
  `github` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`skill` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(80) NULL,
  `level` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- INSERT INTO
-- -----------------------------------------------------

INSERT INTO myself (`firstname`, `lastname`, `role`, `about`, `contact`, `linkedin`, `github`) 
VALUES ('Julien Nicolas', 'Brachet-Randoulet', 'Dev Web Fullstack', 'After 10 years in IT Software development, mainly
          oriented in Java JEE ecosystems, I have decided to go
          for some new challenges.
          Therefore, in the short-term, I aim to enroll on a work-
          study training starting from september 2021.', 'jn.brachet.randlt@gmail.com', '', 'https://github.com/Julien-Brcht-Rndlt');